backend:
  name: git-gateway
  branch: main # or master, depending on your repository
  delete: true # Enable deletion of entries

allowed_roles:
  - admin

publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "species"
    label: "Species"
    folder: "content/species"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Scientific Name", name: "scientific_name", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "cultivars"
    label: "Cultivars / Varieties"
    folder: "content/cultivars"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Parent Species"
        name: "species_link"
        widget: relation
        collection: "species"
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["title"]
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }

  - name: "logs"
    label: "Logs"
    folder: "content/logs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }
      - label: "Cultivar"
        name: "cultivar_link"
        widget: relation
        collection: "cultivars"
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["title"]
